freebsd_instance:
  image_family: freebsd-14-1

iocage_tests_task:
  create_pool_script:
    - truncate -s 20G /root/poolfile
    - zpool create pool /root/poolfile
  install_pkgs_script:
    - sed -i '' 's/quarterly/latest/g' /etc/pkg/FreeBSD.conf
    - pkg install -y git python3 py311-sqlite3
  configure_python_script:
    - python3 -m ensurepip
  freebsd_release_cache:
    folder: ~/freebsd-img/
    populate_script:
      - mkdir -p ~/freebsd-img/14.1-RELEASE
      - fetch -a -m -o ~/freebsd-img/14.1-RELEASE/MANIFEST https://download.freebsd.org/ftp/releases/amd64/14.1-RELEASE/MANIFEST
      - fetch -a -m -o ~/freebsd-img/14.1-RELEASE/base.txz https://download.freebsd.org/ftp/releases/amd64/14.1-RELEASE/base.txz
      - fetch -a -m -o ~/freebsd-img/14.1-RELEASE/lib32.txz https://download.freebsd.org/ftp/releases/amd64/14.1-RELEASE/lib32.txz
      - fetch -a -m -o ~/freebsd-img/14.1-RELEASE/src.txz https://download.freebsd.org/ftp/releases/amd64/14.1-RELEASE/src.txz
  matrix:
    - name: Build python packages
      install_rust_script:
        - pkg install -y rust
      pip_cache:
        folder: ~/.cache/pip
        populate_script:
          - python3 -m pip install -r requirements-test.txt
          - python3 -m pip install -r requirements.txt
          - python3 -m pip install -U cython
      update_cache_script:
        - python3 -m pip install -U -r requirements-test.txt
        - python3 -m pip install -U -r requirements.txt
    - name: Use prebuilt packages
      install_python_packages_script:
        - sed -E 's/([^<>=]+).*/py311-\1/' requirements.txt requirements-test.txt | xargs pkg install -y
        # Necessary as long as py311-pytest a'd py311-pytest-pep8 conflict
        - python3 -m pip install -r requirements-test.txt
  env_setup_script:
    - mount -t fdescfs null /dev/fd
    - pkg install -y devel/py-libzfs
  install_iocage_script:
    - python3 setup.py install
  test_script: pytest --zpool=pool tests/functional_tests --junit-xml=reports/pytest-report.xml -rA
  always:
    pytest_results_artifacts:
      path: reports/*.xml
      format: junit
